insert into users (first_name, last_name, email, password, is_admin) values ('Stavros', 'Frodsam', 'sfrodsam0@vistaprint.com', 'HXbSOzXgWI0K', false);
insert into users (first_name, last_name, email, password, is_admin) values ('Thaddus', 'Blofield', 'tblofield1@theglobeandmail.com', 's9YZEY16oYmI', true);
insert into users (first_name, last_name, email, password, is_admin) values ('Kimberli', 'Roggieri', 'kroggieri2@huffingtonpost.com', '6ov3i3SRsW', false);
insert into users (first_name, last_name, email, password, is_admin) values ('Bernita', 'Hollge', 'bhollge3@issuu.com', 'SBpkEIpemXcY', true);
insert into users (first_name, last_name, email, password, is_admin) values ('Kinsley', 'Dosdell', 'kdosdell4@tmall.com', 'm8DF9YI4E5', true);
insert into users (first_name, last_name, email, password, is_admin) values ('Jordan', 'Corradetti', 'jcorradetti5@w3.org', 'yi9zft',false);
insert into users (first_name, last_name, email, password, is_admin) values ('Joelynn', 'Panketh', 'jpanketh6@google.cn', 'mfCsVLctz',false);
insert into users (first_name, last_name, email, password, is_admin) values ('Dennison', 'Wakeman', 'dwakeman7@cocolog-nifty.com', '6OYb3xuxD', true);
insert into users (first_name, last_name, email, password, is_admin) values ('Steffi', 'Mumbray', 'smumbray8@infoseek.co.jp', 'U5eAV8ux4A', true);
insert into users (first_name, last_name, email, password, is_admin) values ('Eudora', 'Aimeric', 'eaimeric9@netscape.com', 'n0UWj48yfi7q', true);
